buildsys: it was decided just to fail loudly for now if --prefix was not supplied (#590)
git-svn-id: https://www.nest-initiative.uni-freiburg.de/nest/branches/10kproject@10130 4fa6ec7b-3718-0410-b4d6-90ca9082ef84

diff --git a/configure.ac.in b/configure.ac.in
--- a/configure.ac.in
+++ b/configure.ac.in
@@ -28,12 +28,10 @@ else
 fi
 PKGBUILDDIR=`pwd`
 
-# If the user did not supply --prefix, we use $ac_default_prefix. This
-# should make the rest of configure.ac more explicit and thus less prone
-# to errors.
-# JME 2008/06/27
+# If the user did not supply --prefix, we fail loudly
 if test $prefix = NONE; then
-  prefix=$ac_default_prefix
+  echo "Please supply a valid installation prefix, for example ./configure --prefix=\$HOME/opt/nest !"
+  exit 1
 fi
 
 # If this is not called, install-sh will be put into .. by bootstrap.sh
@@ -50,9 +48,6 @@ m4_ifdef([AM_SILENT_RULES], [AM_SILENT_RULES])
 
 # Obtain host system type; HEP 2004-12-20
 AC_CANONICAL_HOST
-
-# Default to installing in the home directory, unless instructed otherwise
-AC_PREFIX_DEFAULT([$HOME/opt/nest])
 
 # ------------------------------------------------------------------------
 # Handle options
